version: '3.3'
services:
  api:
    image: 103738324493.dkr.ecr.us-west-2.amazonaws.com/dashevo/dashdrive
    command: npm run api
    working_dir: ${PWD}
    depends_on:
      - mongodb
      - dashcore
      - ipfs
    volumes:
      - .:${PWD}:delegated
      # this is a workaround to prevent host node_modules from accidentally getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /node_modules location.
      - node_modules:${PWD}/node_modules
    ports:
      - 6000:6000
      - 9229:9229

  sync:
    image: 103738324493.dkr.ecr.us-west-2.amazonaws.com/dashevo/dashdrive
    command: npm run sync
    working_dir: ${PWD}
    depends_on:
      - mongodb
      - dashcore
      - ipfs
    volumes:
      - .:${PWD}:delegated
      # this is a workaround to prevent host node_modules from accidentally getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /node_modules location.
      - node_modules:${PWD}/node_modules
    ports:
      - 9230:9229

  dashcore:
    image: 103738324493.dkr.ecr.us-west-2.amazonaws.com/dashevo/dashcore:develop
    restart: always
    volumes:
      - dashcore:/data
    command: dashd -datadir=/data -regtest=1 -keypool=1 -rpcuser=dashrpc -rpcpassword=password -rpcallowip=0.0.0.0/0 -rpcport=9998 -zmqpubhashblock=tcp://0.0.0.0:29998

  mongodb:
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  ipfs:
    image: ipfs/go-ipfs:4.15
    command: daemon --migrate=true --offline --enable-pubsub-experiment
    volumes:
      - ipfs:/data/ipfs
    ports:
      - 5001:5001

volumes:
  node_modules:
  dashcore:
  mongodb:
  ipfs:
